routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/about', function () {
    return view('about');
});

Route::get('/todo', function () {
    return view('todo');
});
Route::get('/spec', function () {
    return view('spec');
});

Route::post('/tests', function () {
    return view('tests');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*
|
| CRUD routes
|
*/
Route::resource('products', 'ProductsController');
Route::resource('manufacturers', 'ManufacturersController');
Route::resource('orders', 'OrdersController');
Route::resource('admins', 'AdminsController');

/*
| End of Routes file
*/

app/Manufacturer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Manufacturer extends Model
{
    
    /**
     * Relationships.
     *
     * @return void
     */
    public function products(){
        return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/ManufacturersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Manufacturer;
use App\Product;

class ManufacturersController extends Controller
{
        
    /**
    *
    * @return void
    */
    public function __construct()
    {
        $this->middleware('auth' );
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Manufacturers = Manufacturer::orderBy('name', 'asc')->paginate(3);
        return view('manufacturers.index')->with('Manufacturers', $Manufacturers);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('manufacturers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validate input
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required'
        ]);

        // create data item
        $Manufacturer = new Manufacturer;
        $Manufacturer->name = $request->input('name');
        $Manufacturer->slug = $request->input('slug');
        $Manufacturer->description = $request->input('description');
        $Manufacturer->logo = $request->input('logo');
        $Manufacturer->supplier_details = $request->input('supplier_details');
        $Manufacturer->save();

        return redirect('manufacturers')->with('Success', 'Successfully added a Manufacturer');        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $Manufacturer = Manufacturer::find($id);
        $Products = Product::where('manufacturer_id', $Manufacturer->id)->get();
        return view('manufacturers.show')->with('Manufacturer', $Manufacturer)->with('Products', $Products);;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Manufacturer = Manufacturer::find($id);
               
        return view('manufacturers.edit')->with('Manufacturer', $Manufacturer);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Validate input
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required'
        ]);

        // create data item
        $Manufacturer = Manufacturer::find($id);
        $Manufacturer->name = $request->input('name');
        $Manufacturer->slug = $request->input('slug');
        $Manufacturer->description = $request->input('description');
        $Manufacturer->logo = $request->input('logo');
        $Manufacturer->supplier_details = $request->input('supplier_details');
        $Manufacturer->save();

        return redirect('manufacturers')->with('Success', 'Successfully edited a Manufacturer'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Manufacturer = Manufacturer::find($id);
        $Manufacturer->delete();
        return redirect('/manufacturers')->with('Success', 'Successfully removed the Manufacturer');
    }
}

resources/views/manufacturers/create.blade.php
@extends('layouts.app')

@section('content')
    <h2>Add a new Manufacterer</h2>
    
    <form method="POST" action="{{route('manufacturers.store')}}"  >
        @csrf

        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text"  name="name" class="form-control" placeholder="Name" value="" />
        </div>
        <div class="form-group">
            <label for="slug">Slug:</label>
            <input type="text"  name="slug" class="form-control" placeholder="Slug - Alt Name" value="" />
        </div>

        <div class="form-group">
            <label for="logo">logo:</label>
            <input type="text"  name="logo" class="form-control" placeholder="Logo" value="default.jpg" />
        </div>

        <div class="form-group">
            <label for="description">Description:</label>
            <input type="textarea"  name="description" class="form-control" placeholder="Description" value="" />
        </div>

        <div class="form-group">
            <label for="supplier_details">supplier_details:</label>
            <input type="textarea"  name="supplier_details" class="form-control" placeholder="Supplier Details" value="" />
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
        
        <button class="btn btn-secondary ml-4" onclick="history.go(-1)">Cancel</button>

    </form>
@endsection

resources/views/manufacturers/edit.blade.php
@extends('layouts.app')

@section('content')
    <h2>Edit a Manufacterer</h2>
    
    <form method="POST" action="{{route('manufacturers.update', $Manufacturer->id)}}"  >
        <input type="hidden" name="_method" value="PUT" >
        @csrf

        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text"  name="name" class="form-control" placeholder="Name" value="{{$Manufacturer->name}}" />
        </div>
        <div class="form-group">
            <label for="slug">Slug:</label>
            <input type="text"  name="slug" class="form-control" placeholder="Slug - Alt Name" value="{{$Manufacturer->slug}}" />
        </div>

        <div class="form-group">
            <label for="logo">logo:</label>
            <input type="text"  name="logo" class="form-control" placeholder="Logo" value="{{$Manufacturer->logo}}" />
        </div>

        <div class="form-group">
            <label for="description">Description:</label>
            <input type="textarea"  name="description" class="form-control" placeholder="Description" value="{{$Manufacturer->description}}" />
        </div>

        <div class="form-group">
            <label for="supplier_details">supplier_details:</label>
            <input type="textarea"  name="supplier_details" class="form-control" placeholder="Supplier Details" value="{{$Manufacturer->supplier_details}}" />
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
        
        <button class="btn btn-secondary ml-4" onclick="history.go(-1)">Cancel</button>

    </form>
@endsection

resources/views/manufacturers/index.blade.php
@extends('layouts.app')

@section('content')

<h1>Manufacturer Index</h1>

<div>
    <p><a href="/manufacturers/create" class="btn btn-secondary">Create new Manufacturer</a></p>
    
    @if(count($Manufacturers) > 0)
        @foreach($Manufacturers as $Manufacturer)
            <table class="table table-striped">
                <tr>
                    <td colspan="2"><h3><a href="{{ route('manufacturers.show', $Manufacturer->id ) }}" >{{ $Manufacturer->name}}</a><br>{{ $Manufacturer->slug}}</h3></td>
                    <td><a href="/manufacturers/{{$Manufacturer->id}}/edit" class="btn btn-secondary">Edit</a></td>
                    <td>
                        <form method="POST" action="{{ route('manufacturers.destroy', $Manufacturer->id ) }}" >
                            <input type="hidden" name="_method" value="Delete" >
                            @csrf
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
                <tr>
                    <td colspan="4">{{ $Manufacturer->supplier_details}}</td>
                </tr>
                <tr>
                    <td colspan="4"><img src="/img/logos/{{$Manufacturer->logo}}" style="max-width: 200px;"/></td>
                </tr>
            </table>  
        @endforeach
        {{$Manufacturers->links()}}
    @else
        <p>no Manufacturers were found</p>
    @endif
</div> 
@endsection

resources/views/manufacturers/show.blade.php
@extends('layouts.app')

@section('content')

<h1>Show Manufacturer Details</h1>

<div>
    <p>
        <a href="/products/create" class="btn btn-secondary">Create new Manufacturer</a>
        
        @if($Manufacturer)
                <table class="table table-striped">
                    <tr>
                        <td colspan="2"><h3>{{ $Manufacturer->name}}<br>{{ $Manufacturer->slug}}</h3></td>
                        <td><a href="/manufacturers/{{$Manufacturer->id}}/edit" class="btn btn-secondary">Edit</a></td>
                        <td>
                            <form method="POST" action="{{ route('manufacturers.destroy', $Manufacturer->id ) }}" >
                                <input type="hidden" name="_method" value="Delete" >
                                @csrf
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="4">{{ $Manufacturer->supplier_details}}</td>
                    </tr>
                    <tr>
                        <td colspan="4"><img src="/img/products/{{$Manufacturer->logo}}" style="max-width: 200px;"/></td>
                    </tr>

                    @if(count($Products) > 0)
                        @foreach($Products as $Product)                             
                            <tr>
                                <td colspan="4">
                                    <a href="{{ route('products.show', $Product->id ) }}" >{{$Product->name}}</a> <br>
                                    <strong>{{ $Product->type }}</strong> £{{$Product->price}}.{{$Product->pence}}  <br>
                                    {{$Product->description}} <br>

                                </td>
                            </tr>
                        @endforeach 
                    @else
                        <p>no Manufacturer details were found</p>
                    @endif
                
                </table>  
        @else
            <p>no Manufacturers details were found</p>
        @endif                       
        
    </p>
</div> 
@endsection