routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/about', function () {
    return view('about');
});

Route::get('/todo', function () {
    return view('todo');
});
Route::get('/spec', function () {
    return view('spec');
});

Route::post('/tests', function () {
    return view('tests');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*
|
| CRUD routes
|
*/
Route::resource('products', 'ProductsController');
Route::resource('manufacturers', 'ManufacturersController');
Route::resource('orders', 'OrdersController');
Route::resource('admins', 'AdminsController');

/*
| End of Routes file
*/

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    
    /**
     * Relationships.
     *
     * @return void
     */
    public function manufacturer(){
        return $this->belongTo('App\Manufacturer');
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Manufacturer;
use App\Type;

class ProductsController extends Controller
{
        
    /**
    *
    * @return void
    */
    public function __construct()
    {
        $this->middleware('auth' );
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {        
        $Manufacturers = Manufacturer::all();
        $Products = Product::orderBy('name', 'asc')->paginate(3);
        return view('products.index')->with('Products', $Products)->with('Manufacturers', $Manufacturers);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {        
        $Manufacturers = Manufacturer::all();
        $SaxTypes = Type::all();
        return view('products.create')->with('Manufacturers', $Manufacturers)->with('SaxTypes', $SaxTypes);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validate input
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required',
        ]);

        // create data item
        $Product = new Product;
        $Product->name = $request->input('name');
        $Product->slug = $request->input('slug');
        $Product->type = $request->input('type');
        $Product->description = $request->input('description');
        $Product->price = $request->input('price');
        $Product->options = $request->input('options');
        $Product->image = $request->input('image');
        $Product->manufacturer_id = $request->input('manufacturer_id');
        $Product->save();

        return redirect('products')->with('Success', 'Successlly added a Product');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $Product = Product::find($id);
        $Manufacturer = Manufacturer::find($Product->manufacturer_id);
        return view('products.show')->with('Product', $Product)->with('Manufacturer', $Manufacturer);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Product = Product::find($id);
        $Manufacturers = Manufacturer::all();
        $SaxTypes = Type::all();
        return view('/products.edit')->with('Product', $Product)->with('Manufacturers', $Manufacturers)->with('SaxTypes', $SaxTypes);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Validate input
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required',
        ]);

        // create data item
        $Product = Product::find($id);
        $Product->name = $request->input('name');
        $Product->slug = $request->input('slug');
        $Product->type = $request->input('type');
        $Product->description = $request->input('description');
        $Product->price = $request->input('price');
        $Product->options = $request->input('options');
        $Product->image = $request->input('image');
        $Product->manufacturer_id = $request->input('manufacturer_id');
        $Product->save();

        return redirect('products')->with('Success', 'Successlly added a Product');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Product = Product::find($id);
        $Product->delete();
        return redirect('/products')->with('Success', 'Successfully removed the Product');
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <h2>Create a new Product</h2>
    
    <form method="POST" action="{{route('products.store')}}"  >
        @csrf

        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text"  name="name" class="form-control" placeholder="Name" value="" />
        </div>
        
        <div class="form-group">
            <label for="slug">Slug:</label>
            <input type="text"  name="slug" class="form-control" placeholder="Slug - Alt Name" value="" />
        </div>
        
        <div class="form-group">
            <label for="type">Type:</label>
            <select  name="type">
                <option >Please select a type</option>
                @foreach ($SaxTypes as $SaxType)  
                    <option value="{{$SaxType->type}}">{{$SaxType->type}}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="manufacturer_id">Manufacturer:</label>
            <select  name="manufacturer_id">
                <option >Please select a Manufacturer</option>
                @if(count($Manufacturers) > 0)
                    @foreach ($Manufacturers as $Manufacturer)  
                        <option value="{{$Manufacturer->id}}">{{$Manufacturer->name}}</option>
                    @endforeach
                @endif
            </select>
        </div>
        
        <div class="form-group">
            <label for="Price">Price - in pounds:</label>
            <input type="number"  name="price" class="form-control" min="0" value="0" />
        </div>
        
        <div class="form-group">
            <label for="image">Image:</label>
            <input type="text"  name="image" class="form-control" placeholder="Image" value="default.jpg" />
        </div>

        <div class="form-group">
            <label for="description">Description:</label>
            <input type="textarea"  name="description" class="form-control" placeholder="Description" value="" />
        </div>

        <div class="form-group">
            <label for="options">Options:</label>
            <input type="textarea"  name="options" class="form-control" placeholder="Options" value="" />
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
        
        <button class="btn btn-secondary ml-4" onclick="history.go(-1)">Cancel</button>

    </form>

<hr>
<hr>

    {!! Form::open(['url' => 'tests']) !!}

    <div class="form-group">
        {{Form::label('name','Name:') }}
        {{Form::text('name', '', ['class' => 'form-control', 'placeholder' => 'Add product Name' ])}}
    </div>

    <div class="form-group">
        {{Form::label('slug','Slug (Alternate ID value):') }}
        {{Form::text('slug', '', ['class' => 'form-control', 'placeholder' => 'Add Slug' ])}}
    </div>
    
    <div class="form-group">
        {{Form::label('type','Type:') }}
        {{Form::text('type', '', ['class' => 'form-control', 'placeholder' => 'Add Type' ])}}
    </div>
  
    <div class="form-group">
        {{Form::label('manufacturer_id','Manufacturer:') }}
        <select  name="manufacturer_id" class="form-control">
            <option >Please select a Manufacturer</option>
            @if(count($Manufacturers) > 0)
                @foreach ($Manufacturers as $Manufacturer)  
                    <option value="{{$Manufacturer->id}}">{{$Manufacturer->name}}</option>
                @endforeach
            @endif
        </select>
    </div>
    
    
    <div class="form-group">
        {{Form::label('price','Price:') }}
        {{Form::text('Price', '', ['class' => 'form-control', 'placeholder' => 'Add Price' ])}}
    </div>
    
    <div class="form-group">
        {{Form::label('image','Image:') }}
        {{Form::text('image', '', ['class' => 'form-control', 'placeholder' => 'Add product Image' ])}}
    </div>
    
    <div class="form-group">
        {{Form::label('description','Description:') }}
        {{Form::textarea('description', '', ['class' => 'form-control', 'placeholder' => 'Add Description text' ])}}
    </div>
    
    <div class="form-group">
        {{Form::label('options','Options:') }}
        {{Form::textarea('options', '', ['class' => 'form-control', 'placeholder' => 'Add Options text' ])}}
    </div>

    {{ Form::submit('Submit', ['class' => 'btn btn-primary']) }}

    <button class="btn btn-secondary ml-4" onclick="history.go(-1)">Cancel</button>

    {!! Form::close() !!}


@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <h2>Edit a Product</h2>
    
    <form method="POST" action="{{route('products.update', $Product->id)}}"  >
        <input type="hidden" name="_method" value="PUT" >
        @csrf

        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text"  name="name" class="form-control" placeholder="Name" value="{{$Product->name}}" />
        </div>
        
        <div class="form-group">
            <label for="slug">Slug:</label>
            <input type="text"  name="slug" class="form-control" placeholder="Slug - Alt Name" value="{{$Product->slug}}" />
        </div>
        
        <div class="form-group">
            <label for="type">Type:</label>
            <select  name="type">
                @foreach ($SaxTypes as $SaxType)  
                    @if( $Product->type == $SaxType->type) 
                        <option selected value="{{$SaxType->type}}">{{$SaxType->type}}</option> 
                    @else 
                        <option value="{{$SaxType->type}}">{{$SaxType->type}}</option>
                    @endif 
                @endforeach
            </select>
        </div>
        
        <div class="form-group">
            <label for="manufacturer_id">Manufacturer:</label>
            <select  name="manufacturer_id">
                @if(count($Manufacturers) > 0)
                    @foreach ($Manufacturers as $Manufacturer)  
                        @if( $Product->manufacturer_id == $Manufacturer->id) 
                            <option selected value="{{$Manufacturer->id}}">{{$Manufacturer->name}}</option> 
                        @else 
                            <option value="{{$Manufacturer->id}}">{{$Manufacturer->name}}</option>
                        @endif 
                    @endforeach
                @endif
            </select>
        </div>

        <div class="form-group">
            <label for="Price">Price - in pounds:</label>
            <input type="number"  name="price" class="form-control" min="0" value="{{$Product->price}}" />
        </div>
        
        <div class="form-group">
            <label for="image">Image:</label>
            <input type="text"  name="image" class="form-control" placeholder="Image" value="{{$Product->image}}" />
        </div>

        <div class="form-group">
            <label for="description">Description:</label>
            <input type="textarea"  name="description" class="form-control" placeholder="Description" value="{{$Product->description}}" />
        </div>

        <div class="form-group">
            <label for="options">Options:</label>
            <input type="textarea"  name="options" class="form-control" placeholder="Options" value="{{$Product->options}}" />
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
        
        <button class="btn btn-secondary ml-4" onclick="history.go(-1)">Cancel</button>

    </form>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')

<h1>Products Index</h1>

<div>
    <p>
        <a href="/products/create" class="btn btn-secondary">Create new Product</a></p>
    <p>
        @if(count($Products) > 0)
            @foreach($Products as $Product)
                <table class="table table-striped">
                    <tr>
                        <td colspan="2"><h3><a href="{{ route('products.show', $Product->id ) }}" >{{ $Product->name}}</a><br>{{ $Product->slug}}                        </h3></td>
                        <td><a href="/products/{{$Product->id}}/edit" class="btn btn-secondary">Edit</a></td>
                        <td>
                            <form method="POST" action="{{ route('products.destroy', $Product->id ) }}" >
                                <input type="hidden" name="_method" value="Delete" >
                                @csrf
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>

                    <tr>
                        <td colspan="4">
                            Manufacturer: 
                            @if(count($Manufacturers) > 0)
                                @foreach($Manufacturers as $Manufacturer) 
                                    @if($Product->manufacturer_id == $Manufacturer->id) 
                                    {{ $Manufacturer->name}}
                                    @endif
                                @endforeach 
                            @else
                                <p>no Manufacturer details were found</p>
                            @endif 
                        </td>
                    </tr>

                    <tr>
                        <td colspan="2"><strong>{{ $Product->type }}</strong></td>
                        <td colspan="2">&pound{{ $Product->price }}</td>
                    </tr>

                    <tr>
                        <td colspan="4">{{ $Product->description}}</td>
                    </tr>

                    <tr>
                        <td colspan="4">{{ $Product->options}}</td>
                    </tr>
                    <tr>
                        <td colspan="4"><img src="/img/products/{{$Product->image}}" style="max-width: 200px;"/></td>
                    </tr>
                </table>  
            @endforeach
            {{$Products->links()}}
        @else
            <p>no Products were found</p>
        @endif                       
        
    </p>

</div> 
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')

<h1>Products Index</h1>

<div>
    <p>
        <a href="/products/create" class="btn btn-secondary">Create new Product</a>
    </p>

    <p>
        
        @if($Product)
            <table class="table table-striped">
                <tr>
                    <td colspan="2"><h3>{{ $Product->name}}<br>{{ $Product->slug}}                        </h3></td>
                    <td><a href="/products/{{$Product->id}}/edit" class="btn btn-secondary">Edit</a></td>
                    <td>
                        <form method="POST" action="{{ route('products.destroy', $Product->id ) }}" >
                            <input type="hidden" name="_method" value="Delete" >
                            @csrf
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>          
                      
                <tr>
                    <td colspan="4">
                        Manufacturer: 
                        @if($Manufacturer)  
                                {{ $Manufacturer->name}}
                        @else
                            <p>no Manufacturer details were found</p>
                        @endif 
                    </td>
                </tr>

                <tr>
                    <td colspan="2"><strong>{{ $Product->type }}</strong></td>
                    <td colspan="2">&pound{{ $Product->price }}</td>
                </tr>

                <tr>
                    <td colspan="4">{{ $Product->description}}</td>
                </tr>

                <tr>
                    <td colspan="4">{{ $Product->options}}</td>
                </tr>

                <tr>
                    <td colspan="4"><img src="/img/products/{{$Product->image}}" style="max-width: 200px;"/></td>
                </tr>
            </table>  
        @else
            <p>no Products were found</p>
        @endif                       
        
    </p>

</div> 
@endsection