routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/about', function () {
    return view('about');
});

Route::get('/todo', function () {
    return view('todo');
});
Route::get('/spec', function () {
    return view('spec');
});

Route::post('/tests', function () {
    return view('tests');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*
|
| CRUD routes
|
*/
Route::resource('products', 'ProductsController');
Route::resource('manufacturers', 'ManufacturersController');
Route::resource('orders', 'OrdersController');
Route::resource('admins', 'AdminsController');

/*
| End of Routes file
*/

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    
    /**
     * Relationships.
     *
     * @return void
     */
    public function user(){
        return $this->belongTo('App\User');
    }
}

app/Http/Controllers/OrdersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Order;

class OrdersController extends Controller
{
        
    /**
    *
    * @return void
    */
    public function __construct()
    {
        $this->middleware('auth' );
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Orders = Order::orderBy('name', 'asc')->paginate(10);
        return view('orders.index')->with('Orders', $Orders);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/orders/index.blade.php
@extends('layouts.app')

@section('content')

<h1>Orders Index</h1>

<div>
    <p>
        @if(count($Orders) > 0)
            @foreach($Orders as $Order)
                <table class="table table-striped">
                    <tr>
                        <td colspan="2"><h3>{{ $Order->name}}</h3></td>
                        <td><a href="/orders/{{$Order->id}}/edit" class="btn btn-secondary">Edit</a></td>
                        <td>
                            <form method="POST" action="{{ route('orders.destroy', $Order->id ) }}" >
                                <input type="hidden" name="_method" value="Delete" >
                                @csrf
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="4">{{ $Order->description}}</td>
                    </tr>
                </table>  
            @endforeach
            {{$Orders->links()}}
        @else
            <p>no Orders were found</p>
        @endif                       
        
    </p>

    <a href="/orders/create" class="btn btn-secondary">Create new Order</a>
</div> 
@endsection